version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment: 
      ALLOW_EMPTY_PASSWORD: "yes"